% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
% Created Sun Jun 28 13:05:02 IRDT 2015
%
% This script assumes these variables are defined:
%
%   DATA - input data.
%   LAB - target data.

x = DATA;
t = LAB;

% Create a Fitting Network
hiddenLayerSize = 500;
net = fitnet(hiddenLayerSize);


% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;


% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
% y = net(x);
% e = gsubtract(t,y);
% performance = perform(net,t,y)

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotfit(net,x,t)
%figure, plotregression(t,y)
%figure, ploterrhist(e)

